### ISSUE TITLE
Does all NeMo ASR models support in Riva?

### ISSUE THREAD

**Issue by mehadi92** [nvidia-riva/nemo2riva#23]
Does this models support in Riva?

1. conformer model: [STT En Fast Conformer-CTC Large | NVIDIA NGC 1](https://catalog.ngc.nvidia.com/orgs/nvidia/teams/nemo/models/stt_en_fastconformer_ctc_large)
2. Transducer model: [STT En Fast Conformer-Transducer Large | NVIDIA NGC 1](https://catalog.ngc.nvidia.com/orgs/nvidia/teams/nemo/models/stt_en_fastconformer_transducer_large)

**Comment by smallest-admin** [comment]
Hey I am curious to know if these are indeed supported? Because I am getting errors in converting them to riva files.

**Comment by mehadi92** [comment]
@smallest-admin As far I know it's not supported
